// 读书笔记书库数据
(function() {
const BOOK_CATEGORIES = {
  investing: { name: '投资理财', icon: '💰', color: '#10b981' },
  finance: { name: '财务财报', icon: '📊', color: '#3b82f6' },
  philosophy: { name: '哲学佛学', icon: '🧘', color: '#8b5cf6' },
  learning: { name: '学习方法', icon: '📚', color: '#ec4899' },
  management: { name: '组织管理', icon: '🏢', color: '#f59e0b' },
  history: { name: '历史变革', icon: '📜', color: '#ef4444' },
  tech: { name: '科技产业', icon: '🔧', color: '#14b8a6' },
  life: { name: '人生成长', icon: '🌱', color: '#06b6d4' },
  literature: { name: '文学', icon: '📖', color: '#f97316' },
  ungrouped: { name: '未分组', icon: '📋', color: '#64748b' },
};

const BOOKS = [
  // ===== 已读完（40本）=====
  {
    id: '45355190',
    title: '芯片战争',
    author: '余盛',
    category: 'tech',
    progress: 100,
    notes: 382,
    unread: 92,
    starred: 8,
    desc: '讲述全球半导体产业的发展历程，从硅谷到台积电再到中芯国际，展现芯片产业的大国博弈。',
    linkedEntrepreneurs: [],
    sourceId: '45355190',
  },
  {
    id: '44026191',
    title: '纳瓦尔宝典',
    author: '埃里克·乔根森',
    category: 'life',
    progress: 9,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '汇集硅谷投资人纳瓦尔的智慧，涵盖财富创造与幸福人生的核心原则。',
    linkedEntrepreneurs: [],
    sourceId: '44026191',
  },
  {
    id: '25242032',
    title: '投资最重要的事',
    author: '霍华德·马克斯',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '霍华德·马克斯总结数十年的投资经验，阐述价值投资中风险控制与逆向思维的关键。',
    linkedEntrepreneurs: [],
    sourceId: '25242032',
  },
  {
    id: '935891',
    title: '股市进阶之道：一个散户的自我修养',
    author: '李杰',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '从散户视角出发，系统讲解股票投资的进阶方法与自我修炼之道。',
    linkedEntrepreneurs: [],
    sourceId: '935891',
  },
  {
    id: '23934854',
    title: '基金',
    author: '中国证券投资基金业协会编著',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '全面介绍证券投资基金的基础知识与运作机制，是了解基金行业的权威入门读物。',
    linkedEntrepreneurs: [],
    sourceId: '23934854',
  },
  {
    id: '603332',
    title: '巴菲特之道（原书第3版）',
    author: '罗伯特·哈格斯特朗',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '深入解读巴菲特的投资理念与决策方法，揭示其长期制胜的投资逻辑。',
    linkedEntrepreneurs: [],
    sourceId: '603332',
  },
  {
    id: '25623499',
    title: '慢慢变富',
    author: '张居营',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '阐述普通人通过长期稳健投资实现财富增长的朴素道理与实践路径。',
    linkedEntrepreneurs: [],
    sourceId: '25623499',
  },
  {
    id: '34261011',
    title: '徐远的投资课：投资原则与实战方法',
    author: '徐远',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '系统讲解投资的基本原则与实战方法，帮助读者建立完整的投资框架。',
    linkedEntrepreneurs: [],
    sourceId: '34261011',
  },
  {
    id: '29750244',
    title: '投资中最简单的事（全新升级版）',
    author: '邱国鹭',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '邱国鹭以多年从业经验，提炼出投资中简单却常被忽视的核心规律。',
    linkedEntrepreneurs: [],
    sourceId: '29750244',
  },
  {
    id: '3300038268',
    title: '一本书读懂财报',
    author: '肖星',
    category: 'finance',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '用通俗易懂的语言讲解财务报表，帮助非财务人士快速看懂企业财报。',
    linkedEntrepreneurs: [],
    sourceId: '3300038268',
  },
  {
    id: '38334243',
    title: '我的第一本人生规划手册',
    author: '柏永辉',
    category: 'life',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '系统指导人生各阶段的规划方法，涵盖职业、财务与个人成长。',
    linkedEntrepreneurs: [],
    sourceId: '38334243',
  },
  {
    id: '30918459',
    title: 'ETF投资指南',
    author: '老罗',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '详细介绍ETF基金的投资策略与实操技巧，适合指数投资入门者。',
    linkedEntrepreneurs: [],
    sourceId: '30918459',
  },
  {
    id: '3300029476',
    title: '佛教常识答问',
    author: '赵朴初',
    category: 'philosophy',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '赵朴初以问答形式通俗易懂地介绍佛教的基本常识与核心教义。',
    linkedEntrepreneurs: [],
    sourceId: '3300029476',
  },
  {
    id: '34560817',
    title: '雪球专刊·特别版：段永平投资问答录商业逻辑篇',
    author: '雪球专刊',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '汇集段永平关于商业逻辑与投资思考的精华问答，展现其独到的商业洞察。',
    linkedEntrepreneurs: ["duan_yongping"],
    sourceId: '34560817',
  },
  {
    id: '3300076915',
    title: '理工男谈理财：构建受益一生的财富体系',
    author: '王喆',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '以理工科思维系统构建个人理财体系，将理性分析融入财富管理。',
    linkedEntrepreneurs: [],
    sourceId: '3300076915',
  },
  {
    id: '25369877',
    title: '事实（比尔·盖茨推荐）',
    author: '汉斯·罗斯林等',
    category: 'life',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '用数据揭示世界的真实面貌，帮助读者克服认知偏差，用事实思考问题。',
    linkedEntrepreneurs: [],
    sourceId: '25369877',
  },
  {
    id: '436090',
    title: '金刚经讲话',
    author: '星云大师',
    category: 'philosophy',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '星云大师以现代语言逐段讲解《金刚经》，帮助读者领悟般若智慧。',
    linkedEntrepreneurs: [],
    sourceId: '436090',
  },
  {
    id: '937361',
    title: '极简摄影入门',
    author: '杨品等',
    category: 'life',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '以极简方式讲解摄影基础与构图技巧，适合摄影初学者快速上手。',
    linkedEntrepreneurs: [],
    sourceId: '937361',
  },
  {
    id: '3300055219',
    title: '最优解人生',
    author: '比尔·帕金斯',
    category: 'life',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '提出以人生体验最大化为目标的生命规划方法，重新定义财富与时间的关系。',
    linkedEntrepreneurs: [],
    sourceId: '3300055219',
  },
  {
    id: '3300161041',
    title: '投资第1课',
    author: '孟岩',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '孟岩以通俗语言讲解投资入门知识，帮助新手建立正确的投资观念。',
    linkedEntrepreneurs: [],
    sourceId: '3300161041',
  },
  {
    id: '35346608',
    title: '牛市简史：A股五次大牛市的运行逻辑',
    author: '王德伦等',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '回顾A股五次大牛市的演变过程，剖析牛市运行背后的深层逻辑。',
    linkedEntrepreneurs: [],
    sourceId: '35346608',
  },
  {
    id: 'CB_87QGqKGma3v76iX6gW8QB1j7',
    title: '肖星的财务思维课',
    author: '肖星',
    category: 'finance',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '肖星将财务知识转化为管理思维，帮助读者用财务视角理解企业经营。',
    linkedEntrepreneurs: [],
    sourceId: 'CB_87QGqKGma3v76iX6gW8QB1j7',
  },
  {
    id: '3300100788',
    title: '一读就懂的心经',
    author: '王晨阳',
    category: 'philosophy',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '以通俗语言逐句解读《心经》，帮助读者理解这部佛教经典的深刻内涵。',
    linkedEntrepreneurs: [],
    sourceId: '3300100788',
  },
  {
    id: 'CB_EbW1ok1r98Qv6y56x65OUEpl',
    title: '财富捷径',
    author: 'Unknown',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '探索普通人积累财富的实用路径与捷径，提供切实可行的理财建议。',
    linkedEntrepreneurs: [],
    sourceId: 'CB_EbW1ok1r98Qv6y56x65OUEpl',
  },
  {
    id: '3300022102',
    title: '分析：债券市场分析与理解',
    author: '王健',
    category: 'finance',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '系统讲解债券市场的运行机制与分析方法，帮助读者理解固收投资。',
    linkedEntrepreneurs: [],
    sourceId: '3300022102',
  },
  {
    id: '41931030',
    title: '一本书轻松读懂财报',
    author: '大手町的随机漫步者',
    category: 'finance',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '以轻松幽默的方式解读财务报表，让财报阅读变得简单有趣。',
    linkedEntrepreneurs: [],
    sourceId: '41931030',
  },
  {
    id: '855327',
    title: '悉达多（果麦经典）',
    author: '赫尔曼·黑塞',
    category: 'literature',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '黑塞以诗意笔触讲述悉达多求道悟道的一生，探讨自我与精神解脱。',
    linkedEntrepreneurs: [],
    sourceId: '855327',
  },
  {
    id: '3300048810',
    title: '会计地图：一图掌控企业资金动态',
    author: '近藤哲朗等',
    category: 'finance',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '以图表化的方式呈现会计知识，帮助读者直观理解企业资金流转。',
    linkedEntrepreneurs: [],
    sourceId: '3300048810',
  },
  {
    id: '33091830',
    title: '学习之道：美国公认经典学习书',
    author: '乔希·维茨金',
    category: 'learning',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '天才棋手维茨金分享从国际象棋到太极推手的学习方法论，探讨如何精通任何领域。',
    linkedEntrepreneurs: [],
    sourceId: '33091830',
  },
  {
    id: 'CB_D0Y4so4uH1qa6qG6oo67D8vb',
    title: '小狗钱钱',
    author: '博多·舍费尔',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '以童话故事形式讲解理财知识，是风靡全球的财商启蒙经典。',
    linkedEntrepreneurs: [],
    sourceId: 'CB_D0Y4so4uH1qa6qG6oo67D8vb',
  },
  {
    id: '621893',
    title: '世界上最简单的会计书',
    author: '达雷尔·穆利斯等',
    category: 'finance',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '用一个小男孩卖柠檬汁的故事，讲透会计最基本的原理与逻辑。',
    linkedEntrepreneurs: [],
    sourceId: '621893',
  },
  {
    id: '3300056723',
    title: '彼得·林奇投资精要',
    author: '罗尔夫·莫里安等',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '提炼彼得·林奇的投资精华，总结其选股方法与投资智慧。',
    linkedEntrepreneurs: [],
    sourceId: '3300056723',
  },
  {
    id: 'CB_BGmCXECXMEW973h75O1M55TQ',
    title: '命运的求索：中国命理学简史及推演方法',
    author: '陆致极',
    category: 'philosophy',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '系统梳理中国命理学的发展历史与推演方法，兼具学术性与可读性。',
    linkedEntrepreneurs: [],
    sourceId: 'CB_BGmCXECXMEW973h75O1M55TQ',
  },
  {
    id: '3300056725',
    title: '约翰·邓普顿投资精要',
    author: '罗尔夫·莫里安等',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '总结邓普顿爵士的投资理念与逆向投资策略，展现其全球价值投资智慧。',
    linkedEntrepreneurs: [],
    sourceId: '3300056725',
  },
  {
    id: '37730682',
    title: '管理百年',
    author: '斯图尔特·克雷纳',
    category: 'management',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '纵览20世纪管理思想的演进历程，梳理管理学各流派的发展脉络。',
    linkedEntrepreneurs: [],
    sourceId: '37730682',
  },
  {
    id: '3300089715',
    title: '金刚经',
    author: '鸠摩罗什',
    category: 'philosophy',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '鸠摩罗什译《金刚经》，佛教般若经典的核心代表，阐述空性与无住。',
    linkedEntrepreneurs: [],
    sourceId: '3300089715',
  },
  {
    id: '856735',
    title: '如何阅读一本书',
    author: '轻阅读编写组',
    category: 'learning',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '系统介绍不同层次的阅读方法，帮助读者提升阅读效率与理解能力。',
    linkedEntrepreneurs: [],
    sourceId: '856735',
  },
  {
    id: '42541845',
    title: '硬科技：大国竞争的前沿',
    author: '国务院发展研究中心等',
    category: 'tech',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '深度剖析硬科技在大国竞争中的战略地位，展望前沿科技的发展趋势。',
    linkedEntrepreneurs: [],
    sourceId: '42541845',
  },
  {
    id: '42552221',
    title: '销售战神：业绩倍增的销售实战心法',
    author: '娄强',
    category: 'management',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '传授实用的销售技巧与心态修炼方法，帮助销售人实现业绩突破。',
    linkedEntrepreneurs: [],
    sourceId: '42552221',
  },
  {
    id: '3300010685',
    title: '一地鸡毛（典藏版）',
    author: '刘震云',
    category: 'literature',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '刘震云以黑色幽默描写市井生活的琐碎与无奈，折射时代变迁中的小人物命运。',
    linkedEntrepreneurs: [],
    sourceId: '3300010685',
  },
  // ===== 组织管理（1本）=====
  {
    id: '926226',
    title: '10人以下小团队管理手册',
    author: '堀之内克彦',
    category: 'management',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '专为小团队管理者编写的实用指南，聚焦基层管理的核心问题与解决方法。',
    linkedEntrepreneurs: [],
    sourceId: '926226',
  },
  // ===== 股票—长线（2本）=====
  {
    id: '928768',
    title: '巴菲特致股东的信',
    author: '沃伦E.巴菲特等',
    category: 'finance',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '精选巴菲特历年致股东的信，浓缩其投资理念与经营智慧的精华。',
    linkedEntrepreneurs: [],
    sourceId: '928768',
  },
  {
    id: '22297551',
    title: '时间的玫瑰（全新升级版）',
    author: '但斌',
    category: 'finance',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '但斌记录其长期价值投资的心路历程，分享穿越牛熊的投资哲学。',
    linkedEntrepreneurs: [],
    sourceId: '22297551',
  },
  // ===== 钱财投资（7本）=====
  {
    id: '43823280',
    title: '慢慢变富',
    author: '松浦弥太郎',
    category: 'finance',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '松浦弥太郎分享其对金钱与工作的哲学思考，倡导稳健踏实的生活致富观。',
    linkedEntrepreneurs: [],
    sourceId: '43823280',
  },
  {
    id: '43914887',
    title: '传奇投资人的智慧（全7册）',
    author: '罗尔夫·莫里安等',
    category: 'finance',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '汇集多位传奇投资大师的智慧精华，全面呈现价值投资的核心思想。',
    linkedEntrepreneurs: [],
    sourceId: '43914887',
  },
  {
    id: 'CB_3Iy1Aq1Bx2zf6it6gWAmcAJR',
    title: '手把手教你读财报',
    author: '唐朝',
    category: 'finance',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '唐朝以实战视角手把手教读者读懂财报，是财报分析入门的佳作。',
    linkedEntrepreneurs: [],
    sourceId: 'CB_3Iy1Aq1Bx2zf6it6gWAmcAJR',
  },
  {
    id: '3300098818',
    title: '债券投资实战（纪念版）',
    author: '龙红亮',
    category: 'finance',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '系统讲解债券投资的方法与策略，涵盖从入门到进阶的实战内容。',
    linkedEntrepreneurs: [],
    sourceId: '3300098818',
  },
  {
    id: '3300075158',
    title: '邻家的百万富翁',
    author: '托马斯·斯坦利等',
    category: 'finance',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '通过大量调研揭示百万富翁的真实生活与财富习惯，颠覆对富人的刻板印象。',
    linkedEntrepreneurs: [],
    sourceId: '3300075158',
  },
  {
    id: '773704',
    title: '网格交易法',
    author: '林万佳',
    category: 'finance',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '介绍网格交易法的原理与实操，帮助投资者在震荡市中获取稳定收益。',
    linkedEntrepreneurs: [],
    sourceId: '773704',
  },
  {
    id: '920848',
    title: '负利率时代',
    author: '穆罕默德·埃尔-埃里安',
    category: 'finance',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '埃尔-埃里安剖析负利率时代的全球经济格局，探讨投资者的应对策略。',
    linkedEntrepreneurs: [],
    sourceId: '920848',
  },
  // ===== 哲学佛学（6本）=====
  {
    id: '25789833',
    title: '楞严经（佛教十三经）',
    author: '赖永海主编',
    category: 'philosophy',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '佛教重要经典之一，阐述真心与妄心之辨，被誉为"开慧的楞严"。',
    linkedEntrepreneurs: [],
    sourceId: '25789833',
  },
  {
    id: '815185',
    title: '降伏其心（上册）',
    author: '释万行',
    category: 'philosophy',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '释万行法师讲解如何降伏妄心、修持禅定，指引修行者向内探索。',
    linkedEntrepreneurs: [],
    sourceId: '815185',
  },
  {
    id: '569759',
    title: '华杉讲透《孙子兵法》',
    author: '华杉',
    category: 'philosophy',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '华杉以现代视角逐篇解读《孙子兵法》，将古老智慧融入当代商业实践。',
    linkedEntrepreneurs: [],
    sourceId: '569759',
  },
  {
    id: '814697',
    title: '观呼吸：平静的第一堂课',
    author: '德宝法师',
    category: 'philosophy',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '德宝法师系统指导内观禅修的方法，以呼吸为锚点培养正念与平静。',
    linkedEntrepreneurs: [],
    sourceId: '814697',
  },
  {
    id: '3300143757',
    title: '点校本：圆觉经',
    author: '佛陀多罗',
    category: 'philosophy',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '《圆觉经》点校本，阐述圆觉妙心与修行阶位，是佛教大乘重要经典。',
    linkedEntrepreneurs: [],
    sourceId: '3300143757',
  },
  {
    id: '600268',
    title: '了凡四训',
    author: '袁了凡',
    category: 'philosophy',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '袁了凡以自身经历讲述改命立命之理，是流传甚广的劝善修身经典。',
    linkedEntrepreneurs: [],
    sourceId: '600268',
  },
  // ===== 学习方法（6本）=====
  {
    id: '26678294',
    title: '给大忙人的高效阅读课',
    author: '李源',
    category: 'learning',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '为忙碌人群量身定制的阅读方法指南，帮助读者高效汲取书中精华。',
    linkedEntrepreneurs: [],
    sourceId: '26678294',
  },
  {
    id: '3300083972',
    title: '华杉读书笔记',
    author: '华杉',
    category: 'learning',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '华杉分享其阅读经典著作的心得体会，展现从阅读中提炼智慧的方法。',
    linkedEntrepreneurs: [],
    sourceId: '3300083972',
  },
  {
    id: '3300017873',
    title: '榨书：主动成长的高回报读书法',
    author: '格格',
    category: 'learning',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '提出"榨书"理念，教读者如何从一本书中最大化获取知识并实现个人成长。',
    linkedEntrepreneurs: [],
    sourceId: '3300017873',
  },
  {
    id: '924743',
    title: '有效学习',
    author: '乌尔里希·伯泽尔',
    category: 'learning',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '基于认知科学研究成果，系统阐述高效学习的原理与实用方法。',
    linkedEntrepreneurs: [],
    sourceId: '924743',
  },
  {
    id: '3300113800',
    title: '清晰思考：将平凡时刻转化为非凡成果',
    author: '沙恩·帕里什',
    category: 'learning',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '帕里什提供一套清晰的思维框架，帮助读者在平凡时刻做出更好的决策。',
    linkedEntrepreneurs: [],
    sourceId: '3300113800',
  },
  {
    id: '3300063608',
    title: '番茄工作法图解',
    author: '史蒂夫·诺特伯格',
    category: 'learning',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '以图文并茂的方式讲解番茄工作法，帮助读者提升专注力与时间管理能力。',
    linkedEntrepreneurs: [],
    sourceId: '3300063608',
  },
  // ===== 历史变革（1本）=====
  {
    id: '26321245',
    title: '探路之役：1978～1992年的中国经济改革',
    author: '萧冬连',
    category: 'finance',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '详细记述1978至1992年中国经济改革的探索历程，展现改革开放的艰难开局。',
    linkedEntrepreneurs: [],
    sourceId: '26321245',
  },
  // ===== 未分组（19本）=====
  {
    id: '3300080738',
    title: '周期、估值与人性',
    author: '凌鹏',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '凌鹏从周期、估值与人性三个维度，剖析A股市场的运行规律与投资启示。',
    linkedEntrepreneurs: [],
    sourceId: '3300080738',
  },
  {
    id: '3300141458',
    title: '四十二章经（白话版）',
    author: '迦叶摩腾',
    category: 'philosophy',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '中国最早的汉译佛经，以四十二章简要阐述佛法要义，白话版更易理解。',
    linkedEntrepreneurs: [],
    sourceId: '3300141458',
  },
  {
    id: '3300055968',
    title: '命运的求索——中国命理学简史及推演方法',
    author: '陆致极',
    category: 'philosophy',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '系统梳理中国命理学的发展历史与推演方法，兼具学术性与可读性。',
    linkedEntrepreneurs: [],
    sourceId: '3300055968',
  },
  {
    id: '30762982',
    title: '肖星的财务思维课',
    author: '肖星',
    category: 'finance',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '肖星将财务知识转化为管理思维，帮助读者用财务视角理解企业经营。',
    linkedEntrepreneurs: [],
    sourceId: '30762982',
  },
  {
    id: '436087',
    title: '星云大师《心经》五讲',
    author: '星云大师',
    category: 'philosophy',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '星云大师分五个层次讲解《心经》，层层递进揭示般若空性智慧。',
    linkedEntrepreneurs: [],
    sourceId: '436087',
  },
  {
    id: '26796443',
    title: '增广贤文（国学大书院）',
    author: '佚名',
    category: 'philosophy',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '中国古代蒙学经典，汇集历代格言谚语，蕴含丰富的人生智慧与处世哲学。',
    linkedEntrepreneurs: [],
    sourceId: '26796443',
  },
  {
    id: '33831339',
    title: 'B端产品经理必修课2.0',
    author: '李宽',
    category: 'management',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '系统讲解B端产品经理的核心能力与工作方法，助力产品经理职业进阶。',
    linkedEntrepreneurs: [],
    sourceId: '33831339',
  },
  {
    id: '35679924',
    title: '雪球专刊·特别版：段永平投资问答录投资逻辑篇',
    author: '雪球专刊',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '汇集段永平关于投资逻辑的精华问答，深入展现其价值投资思维体系。',
    linkedEntrepreneurs: ["duan_yongping"],
    sourceId: '35679924',
  },
  {
    id: '3300143764',
    title: '点校本：金刚经',
    author: '鸠摩罗什',
    category: 'philosophy',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '《金刚经》点校本，以鸠摩罗什译本为基础，校勘精审便于研读。',
    linkedEntrepreneurs: [],
    sourceId: '3300143764',
  },
  {
    id: '3300015063',
    title: '张一鸣管理日志',
    author: '林军等',
    category: 'management',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '以日志体记录张一鸣的管理理念与创业思考，展现字节跳动的管理哲学。',
    linkedEntrepreneurs: ["zhang_yiming"],
    sourceId: '3300015063',
  },
  {
    id: 'CB_42T4q14q81qa6qG6ooCO49H4',
    title: '小狗钱钱',
    author: '博多·舍费尔',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '以童话故事形式讲解理财知识，是风靡全球的财商启蒙经典。',
    linkedEntrepreneurs: [],
    sourceId: 'CB_42T4q14q81qa6qG6ooCO49H4',
  },
  {
    id: '3300109339',
    title: '大师我悟了',
    author: '胡适等',
    category: 'literature',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '收录胡适等大师的哲理散文，探讨人生、学问与觉悟的深刻命题。',
    linkedEntrepreneurs: [],
    sourceId: '3300109339',
  },
  {
    id: '3300082585',
    title: '康奈尔学习法：从记笔记开始，成就终身学习',
    author: '友荣方略',
    category: 'learning',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '系统介绍康奈尔笔记法及其在学习中的应用，帮助构建高效学习体系。',
    linkedEntrepreneurs: [],
    sourceId: '3300082585',
  },
  {
    id: '3300144581',
    title: '现代文：素书',
    author: '黄石公',
    category: 'philosophy',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '《素书》现代文译本，相传为黄石公所作，以简练语言阐述治世修身之道。',
    linkedEntrepreneurs: [],
    sourceId: '3300144581',
  },
  {
    id: '22737128',
    title: '觉悟的生活：星云大师讲《心经》',
    author: '星云大师',
    category: 'philosophy',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '星云大师以生活化的语言讲解《心经》，引导读者将般若智慧融入日常。',
    linkedEntrepreneurs: [],
    sourceId: '22737128',
  },
  {
    id: '23839264',
    title: '妙趣横生的国债期货',
    author: '王舟',
    category: 'investing',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '以生动有趣的方式讲解国债期货知识，让枯燥的金融衍生品变得通俗易懂。',
    linkedEntrepreneurs: [],
    sourceId: '23839264',
  },
  {
    id: '130224',
    title: '全中国最穷的小伙子发财日记',
    author: '重庆老康',
    category: 'life',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '以日记形式记录一个普通人的奋斗与致富历程，充满草根逆袭的真实力量。',
    linkedEntrepreneurs: [],
    sourceId: '130224',
  },
  {
    id: '3300148025',
    title: '一个人变富，从学会独处开始',
    author: '洞见君',
    category: 'life',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '探讨独处与财富积累的关系，倡导通过内心成长实现人生富足。',
    linkedEntrepreneurs: [],
    sourceId: '3300148025',
  },
  {
    id: '3300014694',
    title: '有限与无限的游戏',
    author: '詹姆斯·卡斯',
    category: 'philosophy',
    progress: 0,
    notes: 0,
    unread: 0,
    starred: 0,
    desc: '卡斯以哲学视角区分有限游戏与无限游戏，启发读者重新审视人生的意义与方向。',
    linkedEntrepreneurs: [],
    sourceId: '3300014694',
  },
];

window.BOOKS_DATA = { BOOK_CATEGORIES, BOOKS };
})();
